// eslint-disable-next-line no-unused-vars
type EventString =
  | 'ready'
  | 'channelCreate'
  | 'channelDelete'
  | 'channelUpdate'
  | 'guildBanAdd'
  | 'guildBanRemove'
  | 'guildCreate'
  | 'guildDelete'
  | 'guildMemberAdd'
  | 'guildMemberRemove'
  | 'guildMemberUpdate'
  | 'guildRoleCreate'
  | 'guildRoleUpdate'
  | 'guildUpdate'
  | 'inviteCreate'
  | 'inviteDelete'
  | 'messageCreate'
  | 'messageDelete'
  | 'messageReactionRemoveEmoji'
  | 'messageDeleteBulk'
  | 'messageReactionAdd'
  | 'messageReactionRemove'
  | 'typingStart'
  | 'userUpdate'
  | 'voiceChannelJoin'
  | 'voiceChannelLeave';
